name: Docker Image [emscripten]

on:
  push:
    tags:
      - emscripten-v*

jobs:
  build:
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image [emscripten]
        run: |
          docker build ./docker --file docker/Dockerfile.emscripten --tag emscripten

      - name: Push image [emscripten]
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^emscripten-v//')-pre

          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

          docker tag emscripten $GITHUB_DOCKER_REPOSITORY/emscripten:$VERSION
          docker push $GITHUB_DOCKER_REPOSITORY/emscripten:$VERSION

          docker logout
