name: Docker Image [ubuntu1804]

on:
  push:
    tags:
      - ubuntu1804-v*

jobs:
  build:
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image [ubuntu1804]
        run: |
          docker build ./docker --file docker/Dockerfile.ubuntu1804 --tag ubuntu1804

      - name: Push image [ubuntu1804]
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^ubuntu1804-v//')-pre

          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

          docker tag ubuntu1804 $GITHUB_DOCKER_REPOSITORY/ubuntu1804:$VERSION
          docker push $GITHUB_DOCKER_REPOSITORY/ubuntu1804:$VERSION

          docker logout
